#!/bin/bash

# Set the default session to openbox
session_default=gnome

# Allow specifying a session with startx
session=$2
test -z "$session" && session=$session_default

# Start the URxvt daemon
urxvtd -q -o -f &

# Turn numlock on
[[ -x "/usr/bin/numlockx" ]] && numlockx &

# Restore the previous background
#eval `cat ~/.fehbg` &

case $session in
    "gnome")
        alunn &
        fusion-icon &
        exec gnome-session;;

    "openbox")
        #pypanel &
        trayer --expand true --widthtype request --height 16 --edge top --align left &
        tint &
        conky &
        alunn &
        glipper-old &
        gnome-settings-daemon &
        thunar --daemon &
        exec openbox-session;;

    "openbox-gnome")
        exec openbox-gnome-session;;

    "kde")
        exec startkde;;

    "awesome")
        if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
            eval `dbus-launch --sh-syntax --exit-with-session`
        fi

        #xcompmgr -cC -t-2 -l-3 -r3 -o.30 &
        thunar --daemon &
        gnome-settings-daemon &
        alunn &
        glipper-old &
#        sonata --hidden &

        /usr/local/bin/awesome-status &
        sleep 1
#        trayer --expand true --widthtype request --height 16 --edge bottom --align right &
        exec awesome;;
    *)

esac
