#!/bin/bash

sleep 2;

while ! pgrep awesome >/dev/null
do
    echo "waiting for 'awsome-wm' to start"
    sleep 2;
done

/usr/local/bin/awesome-status.awk <<< "" | awesome-client

# the awk stript needs some bogus input in order to start right away (<<< "")
